### ISSUE TITLE
Install on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by dpengftw** [osodevops/ansible-role-cardano-node#1]
Below is the output:

` ~  ansible-playbook playbook.yml                                                          ok | took 16s | at 20:36:19

PLAY [all] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host node.peng168.com should use /usr/bin/python3, but is using
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using
the discovered platform python for this host. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature
 will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
ok: [node.peng168.com]

TASK [sionsmith.cardano_node : Server Setup | Set timezone to Europe/London] *******************************************
ok: [node.peng168.com]

TASK [sionsmith.cardano_node : Server Setup | Set hostname of installer to static value] *******************************
changed: [node.peng168.com]

TASK [sionsmith.cardano_node : Server Setup | Make sure we have a 'wheel' group] ***************************************
ok: [node.peng168.com]

TASK [sionsmith.cardano_node : Server Setup | Allow 'wheel' group to have passwordless sudo] ***************************
ok: [node.peng168.com]

TASK [sionsmith.cardano_node : Server Setup | Add sudoers users to wheel group] ****************************************
ok: [node.peng168.com]

TASK [sionsmith.cardano_node : Server Setup | Create .ssh directory for cardano user] **********************************
ok: [node.peng168.com]

TASK [sionsmith.cardano_node : Server Setup | Create .local/bin directory for cardano user] ****************************
ok: [node.peng168.com]

TASK [sionsmith.cardano_node : Package Install | Install Yum Dependencies] *********************************************
fatal: [node.peng168.com]: FAILED! => {"ansible_facts": {"pkg_mgr": "apt"}, "changed": false, "msg": "No package matching 'gcc-c++' is available"}

PLAY RECAP *************************************************************************************************************
node.peng168.com           : ok=8    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0`

**Comment by sionsmith** [comment]
@jedioncrk Current this role only works on Amazon Linux 2 - is there a reason why you want to use ubuntu?

**Comment by dpengftw** [comment]
I'm not running in AWS.  I would have assumed that Ubuntu would be a fairly popular option.
